sudo: false
language: node_js
node_js:
- '2'
- '1'
- '0.12'
- '0.10'
- '0.8'
before_install:
- git submodule update --init --recursive
- ruby -e "\`npm i -g npm@2\` if '`npm -v`'<'2.0.0'"
notifications:
  email:
    recipients:
    - z@apiary.io
    on_success: change
    on_failure: always
  slack:
    secure: Kw0lRYBknqm2a+N94lfi6Jo9941yYjsmCvNOnrjlsinTjlN47Yog0va97/3OWflz+LbAZ5dJgeIK2/XvDqDNppynjDdJJikAM5G7OAWCzwmF8u97PONLLL9CnQECF9ZC8j4jIpnkSPPrJCor02EbJA9Uz7wjscrEjT7Dd529TP0=
