# Test against this version of Node.js
os: Visual Studio 2015 CTP

environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"

# Install scripts. (runs after repo cloning)
install:
  # Fetch project submodules
  - git submodule update --init --recursive
  # Get the latest stable version of Node.js or io.js
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
