image:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"

install:
  - git submodule update --init --recursive
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm test

# Don't actually build.
build: off
