version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

  environment:
    CC: gcc-7
    CXX g++-7

aliases:
  - &install-compiler
    run:
      name: Installing Compiler
      command: |
        sudo sh -c 'echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" > /etc/apt/sources.list.d/unstable.list'
        sudo apt-get update
        sudo apt-get install -y -t unstable gcc-7 g++-7

jobs:
  test:
    <<: *defaults
    steps:
      - <<: *install-compiler
      - checkout
      - run: git submodule update --init --recursive
      - run: npm install
      - run: npm test
      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-publish:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
